<div class="wrapper" id="grtDataContainer" style="display: none;">
								<div style="float: left; width: 100%;">
									<div class="floatLeft">
										<label>Long Term</label>
									</div>
									<div class="floatLeft width_71_p pad_5" style="float: left;margin-right: 20px;">
										<table frame="box" rules="all" cellpadding="3"
											id="tblLongTerm">
											<tr>
												<th></th>
												<th colspan="9">GROWTH</th>
											</tr>
											<tr>
												<td rowspan="12"><div
														class="toptobottom pad_7 mar_right_3 mar_left_-3" style="-ms-transform: rotate(-90deg); /* IE 9 */-webkit-transform: rotate(-90deg); /* Chrome, Safari, Opera */transform: rotate(-90deg);">RETURN</div></td>
												<td></td>
												<td>1%</td>
												<td>2%</td>
												<td>3%</td>
												<td>4%</td>
												<td>5%</td>
												<td>6%</td>
												<td>7%</td>
												<td>8%</td>
											</tr>
											<tr>
												<td>4%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>5%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>6%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>7%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>8%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>9%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>10%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>11%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>12%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>13%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>14%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
										</table>
									</div>
									<div class="floatLeft mar_left_50 pad_5" id="tbl_rt_LongTerm">
										<table frame="box" rules="all" cellpadding="3">
											<tr>
												<td>Average Rent</td>
												<td></td>
											</tr>
											<tr>
												<td>Average Price</td>
												<td></td>
											</tr>
											<tr>
												<td>Median</td>
												<td></td>
											</tr>
											<tr>
												<td>Mode</td>
												<td></td>
											</tr>
											<tr>
												<td>stDev</td>
												<td></td>
											</tr>
											<tr>
												<td>Varience</td>
												<td></td>
											</tr>
											<tr>
												<td>Kurtosis</td>
												<td></td>
											</tr>
											<tr>
												<td>Skewness</td>
												<td></td>
											</tr>
											<tr>
												<td>Min</td>
												<td></td>
											</tr>
											<tr>
												<td>Max</td>
												<td></td>
											</tr>
											<tr>
												<td>Sum</td>
												<td></td>
											</tr>
											<tr>
												<td>Volume</td>
												<td>2531314.29</td>
											</tr>
										</table>
									</div>
								</div>

								<div style="margin-top: 30px;">
									<div class="shortterm">
										<label>Short Term</label>
									</div>

									<div class="floatLeft width_71_p pad_5" style="float: left;margin-right: 20px;">
										<table frame="box" rules="all" cellpadding="3"
											id="tblShortTerm">
											<tr>
												<th></th>
												<th colspan="9">GROWTH</th>
											</tr>
											<tr>
												<td rowspan="12"><div
														class="toptobottom pad_7 mar_right_3 mar_left_-3" style="-ms-transform: rotate(-90deg); /* IE 9 */-webkit-transform: rotate(-90deg); /* Chrome, Safari, Opera */transform: rotate(-90deg);">RETURN</div></td>
												<td></td>
												<td>1%</td>
												<td>2%</td>
												<td>3%</td>
												<td>4%</td>
												<td>5%</td>
												<td>6%</td>
												<td>7%</td>
												<td>8%</td>
											</tr>
											<tr>
												<td>4%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>5%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>6%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>7%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>8%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>9%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>10%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>11%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>12%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>13%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
											<tr>
												<td>14%</td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
												<td></td>
											</tr>
										</table>
									</div>
									<div class="floatLeft mar_left_50 pad_5">
										<table frame="box" rules="all" cellpadding="3"
											id="tbl_rt_ShortTerm">
											<tr>
												<td>Average Rent</td>
												<td></td>
											</tr>
											<tr>
												<td>Average Price</td>
												<td></td>
											</tr>
											<tr>
												<td>Median</td>
												<td></td>
											</tr>
											<tr>
												<td>Mode</td>
												<td></td>
											</tr>
											<tr>
												<td>stDev</td>
												<td></td>
											</tr>
											<tr>
												<td>Varience</td>
												<td></td>
											</tr>
											<tr>
												<td>Kurtosis</td>
												<td></td>
											</tr>
											<tr>
												<td>Skewness</td>
												<td></td>
											</tr>
											<tr>
												<td>Min</td>
												<td></td>
											</tr>
											<tr>
												<td>Max</td>
												<td></td>
											</tr>
											<tr>
												<td>Sum</td>
												<td></td>
											</tr>
											<tr>
												<td>Volume</td>
												<td>2531314.29</td>
											</tr>
										</table>
									</div>
								</div>
							</div>